### ISSUE TITLE
Question about ND and CJD

### ISSUE THREAD

**Issue by hoebat** [clojure-goes-fast/clj-java-decompiler#2]
In the readme, it says:

- ND can disassemble any already defined Clojure function. CJD needs the Clojure form to be passed directly to it.

Is there a reason why this is the case?

**Comment by alexander-yakushev** [comment]
Yes. Java doesn't keep the bytecode for classes it loaded anywhere. So, ND works by being a Java agent which instruments the classloader to save all classes it ever loaded into an accessible hashmap, so that they can be retrieved later. This creates two inconveniences:

- You must start your Clojure app with the agent.
- Bytecode is never evicted from the hashmap, and that might creates memory problems if you load a lot of classes/recompile a lot.

In contrast to ND, CJD is just a library and can be hotloaded at any point of your program. You can decompile arbitrary forms, not just functions, which is extra useful for inspecting things like `deftype`, `defrecord`, etc.

Regarding the potential drawback that you can't decompile an already defined 3rd-party function: Clojure IDEs (CIDER, at least) allow you to jump to a function definition even inside the jar. There, it is usually trivial to wrap the function in `(decompile ...)` and recompile it.

**Comment by hoebat** [comment]
ah yes. thanks for the explanation. I really like the fact that this doesn't require an agent. This is great. It's what I'm looking for.

**Comment by xificurC** [comment]
The explanation and the tips could be pulled in the README

**Comment by alexander-yakushev** [comment]
There's already a block in the readme comparing with ND, are you seeing something here that's not in there?

**Comment by xificurC** [comment]
The fact one cannot disassemble already defined classes is there. The reason why (which is the question of this issue) is not there. The tip to jump to the definition and recompile it is a nice bonus too.

Thinking more about this, wouldn't it be possible for `(decompile pprint)` to look up pprint's corresponding class file on the classpath and use that?

**Comment by alexander-yakushev** [comment]
> Thinking more about this, wouldn't it be possible for (decompile pprint) to look up pprint's corresponding class file on the classpath and use that?

That, unfortunately, would work only for AOT-compiled classes (only Clojure core library, basically).

**Comment by xificurC** [comment]
Interesting. Would you mind enlightening me why? I always thought if something is callable it has already been compiled into a class file (by calling `require` or other similar means).

**Comment by alexander-yakushev** [comment]
As I've written earlier,

> Java doesn't keep the bytecode for classes it loaded anywhere.

Meaning the Clojure compiler compiles Clojure code to bytecode, immediately loads it with the classloader, and then discards the bytecode. No .class files are written unless `*compile-files*` is set to true.

**Comment by xificurC** [comment]
I see. I read that sentence but didn't connect the dots. Thanks for this great library (as well as many others)

**Comment by alexander-yakushev** [comment]
You are welcome! I've updated the README to include the information you requested.

**Comment by xificurC** [comment]
Nice, thank you
